export const blogPosts = [
  {
    slug: `ai-roi-click2save-fitness`,
    title: `The CFO's Guide to AI ROI: Unpacking Click2Save for Fitness Centers`,
    image: `/blogo/CFO ROI.jpg`,
    description: `An in-depth look at how AI-driven solutions like Click2Save can deliver measurable ROI for fitness centers.`,
    html: `/docz/What-CFOs-Need-to-Know-About-Click2Save-ROI.html`,
    content: ``,
  },
  {
    slug: `ai-adoption-fitness-operations`,
    title: `The Real Cost of Inaction: AI Adoption in Fitness Operations`,
    image: `/blogo/Costly choice.png`,
    description: `Exploring the operational and financial risks of delaying AI adoption in the fitness industry.`,
    html: `/docz/AI-Adoption-in-Fitness-Operations_-Why-Waiting-Is-the-Costliest-Option.html`,
    content: ``,
  },
  {
    slug: `ai-stopped-gym-cancellation`,
    title: `"I Almost Canceled, But AI Stopped Me"`,
    image: `/blogo/C2S-Marty.jpg`,
    description: `A case study on how AI-powered member engagement can prevent gym cancellations.`,
    html: `/docz/I-Tried-to-Cancel-My-Gym-Membership—Here's-How-an-AI-Saved-Me-Instead.html`,
    content: ``,
  },
  {
    slug: `how-ai-helps-fitness-clubs-fight-tariff-costs`,
    title: `How AI Helps Fitness Clubs Fight Rising Tariff Costs`,
    image: `/blogo/Tariff Fitness.jpg`,
    description: `Discover how AI can optimize operations and offset the financial impact of rising tariffs on fitness clubs.`,
    html: `/docz/Tariffs-Are-Squeezing-Fitness-Clubs-—-Here's-How-AI-Can-Help-You-Fight-Back.html`,
    content: ``,
  },
  {
    slug: 'the-compliance-trap',
    title: 'The Compliance Trap',
    image: '/blogo/Compliance Trap.jpg',
    description: 'How to avoid the compliance trap in the fitness industry.',
    html: '/docz/The-Compliance-Trap.html',
    content: '',
  },
  {
    slug: 'navigating-gym-membership-cancellation-laws',
    title: 'Navigating Gym Membership Cancellation Laws',
    image: '/blogo/Navigating membership.jpg',
    description: 'A guide to understanding and complying with gym membership cancellation laws.',
    html: '/docz/Navigating-Gym-Membership-Cancellation-Laws_.html',
    content: '',
  },
  {
    slug: 'harnessing-data-ai-retention',
    title: 'Harnessing Data and AI to Enhance Fitness Member Retention',
    image: '/blogo/Data Improves Retention.jpg',
    description: 'Strategies for using data and AI to build stronger member relationships and boost retention.',
    html: '/docz/Harnessing-Data-and-Generative-AI-to-Enhance-Fitness-Member-Retention.html',
    content: '',
  },
  {
    slug: '24-7-service-without-the-overhead',
    title: '24/7 Service Without the Overhead',
    image: '/blogo/Agentic AI Now.jpg',
    description: 'Provide around-the-clock service to your members without increasing your overhead.',
    html: '/docz/24_7-Service-Without-the-Overhead__.html',
    content: '',
  }
];